//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH911ECU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RRHHECU911Entities : DbContext
    {
        public RRHHECU911Entities()
            : base("name=RRHHECU911Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_CargoInstitucional> Tbl_CargoInstitucional { get; set; }
        public virtual DbSet<Tbl_CorreoIntitucional> Tbl_CorreoIntitucional { get; set; }
        public virtual DbSet<Tbl_DireccionInstitucional> Tbl_DireccionInstitucional { get; set; }
        public virtual DbSet<Tbl_Discapacidad> Tbl_Discapacidad { get; set; }
        public virtual DbSet<Tbl_Emp_Per> Tbl_Emp_Per { get; set; }
        public virtual DbSet<Tbl_Empresa> Tbl_Empresa { get; set; }
        public virtual DbSet<Tbl_EstrcuturaUno> Tbl_EstrcuturaUno { get; set; }
        public virtual DbSet<Tbl_EstructuraDos> Tbl_EstructuraDos { get; set; }
        public virtual DbSet<Tbl_EstructuraProgramatica> Tbl_EstructuraProgramatica { get; set; }
        public virtual DbSet<Tbl_Grado> Tbl_Grado { get; set; }
        public virtual DbSet<Tbl_GrupoEtnico> Tbl_GrupoEtnico { get; set; }
        public virtual DbSet<Tbl_GrupoOcupacional> Tbl_GrupoOcupacional { get; set; }
        public virtual DbSet<Tbl_Identidad_de_Genero> Tbl_Identidad_de_Genero { get; set; }
        public virtual DbSet<Tbl_Inicial> Tbl_Inicial { get; set; }
        public virtual DbSet<Tbl_ModalidadLaboral> Tbl_ModalidadLaboral { get; set; }
        public virtual DbSet<Tbl_OrientacionSexual> Tbl_OrientacionSexual { get; set; }
        public virtual DbSet<Tbl_Personas> Tbl_Personas { get; set; }
        public virtual DbSet<Tbl_ProcesoInterno> Tbl_ProcesoInterno { get; set; }
        public virtual DbSet<Tbl_Religion> Tbl_Religion { get; set; }
        public virtual DbSet<Tbl_Rmu> Tbl_Rmu { get; set; }
        public virtual DbSet<Tbl_Sede> Tbl_Sede { get; set; }
        public virtual DbSet<Tbl_TelefonoIntitucional> Tbl_TelefonoIntitucional { get; set; }
        public virtual DbSet<Tbl_Zona> Tbl_Zona { get; set; }
    }
}
