//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH911ECU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Empresa()
        {
            this.Tbl_Emp_Per = new HashSet<Tbl_Emp_Per>();
        }
    
        public int Emp_id { get; set; }
        public string Emp_nombre { get; set; }
        public Nullable<int> Emp_ruc { get; set; }
        public Nullable<int> Emp_ciiu { get; set; }
        public string Emp_estabSalud { get; set; }
        public string Emp_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Emp_Per> Tbl_Emp_Per { get; set; }
    }
}
