//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH911ECU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inicial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Inicial()
        {
            this.Tbl_Emp_Per = new HashSet<Tbl_Emp_Per>();
            this.Tbl_Personas = new HashSet<Tbl_Personas>();
        }
    
        public int inicial_id { get; set; }
        public Nullable<int> inicial_edad { get; set; }
        public string inicial_NumArchivo { get; set; }
        public Nullable<int> Rel_id { get; set; }
        public string inicial_groSanguineo { get; set; }
        public string inicial_lateralidad { get; set; }
        public Nullable<int> OrSex_id { get; set; }
        public Nullable<int> IdtGen_id { get; set; }
        public Nullable<int> Dis_id { get; set; }
        public string inicial_fechIngTrabajo { get; set; }
        public Nullable<System.DateTime> inicial_fechSalida { get; set; }
        public Nullable<int> inicial_tiempo { get; set; }
        public string inicial_puesTrabajo { get; set; }
        public string inicial_Actividades { get; set; }
        public string inicial_facRiesgo { get; set; }
        public string inicial_areaTrabajo { get; set; }
        public string inicial_actsRelevantes { get; set; }
        public Nullable<int> Act_id { get; set; }
        public Nullable<int> FacR_id { get; set; }
        public string inicial_estado { get; set; }
    
        public virtual Tbl_Discapacidad Tbl_Discapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Emp_Per> Tbl_Emp_Per { get; set; }
        public virtual Tbl_Identidad_de_Genero Tbl_Identidad_de_Genero { get; set; }
        public virtual Tbl_OrientacionSexual Tbl_OrientacionSexual { get; set; }
        public virtual Tbl_Religion Tbl_Religion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Personas> Tbl_Personas { get; set; }
    }
}
