//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH911ECU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Emp_Per
    {
        public int EmpPer_id { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public Nullable<int> Per_id { get; set; }
    
        public virtual Tbl_Empresa Tbl_Empresa { get; set; }
        public virtual Tbl_Inicial Tbl_Inicial { get; set; }
    }
}
